# coding=utf-8
# How many distinct terms are in the sequence generated by a**b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
from comm import timed

@timed
def organizePowers2(min,max):
    return len(set(a**b for a in range(min, max+1) for b in range(min,max+1)))

if __name__ == "__main__":
    print(organizePowers2(2,100))