# coding=utf-8
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.
from comm import timed
import comm

@timed
def p45():
    n = 143
    while True:
        n+=1
        x = n*(2*n-1)
        y, z = comm.isPent(x)
        if y:
            a,b = comm.isTri(x)
            return f"T{b} = P{z} = H{n} = {x}"

print(p45())
